apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-service
    spec:
      containers:
      - name: fastapi-container
        image: python:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: fastapi-config
        - secretRef:
            name: fastapi-secret

